# Generated by Django 4.1.4 on 2023-01-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('ticker', models.CharField(max_length=5)),
                ('pricing_history', models.JSONField()),
            ],
        ),
    ]
