# Generated by Django 4.1.4 on 2023-01-03 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockdata',
            unique_together={('ticker', 'date_added')},
        ),
    ]
